"""Powers GET /evaluation (demo Tab 3 "비교"):
- extraction metrics against a small hand-labeled goldset of sample
  conversations, matched on (field, value) with lenient substring matching
  since slot wording can legitimately vary a little from the gold label.
- a rollup of recent ValidationLog rows, showing how many rule violations
  remain in itineraries actually generated by the running backend."""

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.validation_log import ValidationLog
from app.services.kakao_parser import parse
from app.services.slot_extractor import SlotExtractionError, SlotExtractor, slot_extractor

GOLDSET: list[dict] = [
    {
        "conversation": (
            "--------------- 2025년 6월 20일 ---------------\n"
            "2025년 6월 20일 오후 3:41, 김주연 : 이번 여행 부산으로 가자\n"
            "2025년 6월 20일 오후 3:42, 강경래 : 좋아 부산!! 회 맛집 꼭 가고 싶어\n"
            "2025년 6월 20일 오후 3:43, 김주연 : ㅇㅇ 예산은 1인당 30만원 정도로 하자\n"
            "2025년 6월 20일 오후 3:44, 강경래 : 콜! 인원은 우리 둘이니까 2명이네\n"
        ),
        "gold_slots": [
            {"field": "destination", "value": "부산"},
            {"field": "wishlist", "value": "회 맛집"},
            {"field": "budget", "value": "30만원"},
            {"field": "headcount", "value": "2명"},
        ],
    },
]


@dataclass
class ExtractionMetrics:
    precision: float | None
    recall: float | None
    f1: float | None
    error: str | None = None


def _values_match(gold_value: str, extracted_value: str) -> bool:
    gold_norm = gold_value.strip().lower()
    extracted_norm = extracted_value.strip().lower()
    return gold_norm in extracted_norm or extracted_norm in gold_norm


def evaluate_extraction(extractor: SlotExtractor | None = None) -> ExtractionMetrics:
    extractor = extractor or slot_extractor
    true_positives = 0
    predicted_count = 0
    gold_count = 0

    try:
        for case in GOLDSET:
            parse_result = parse(case["conversation"])
            extraction = extractor.extract(parse_result.messages)
            confirmed = [slot for slot in extraction.slots if slot.status.value == "confirmed"]
            predicted_count += len(confirmed)
            gold_count += len(case["gold_slots"])

            matched_gold_indices: set[int] = set()
            for slot in confirmed:
                for i, gold in enumerate(case["gold_slots"]):
                    if i in matched_gold_indices:
                        continue
                    if slot.field.value == gold["field"] and _values_match(gold["value"], slot.value):
                        true_positives += 1
                        matched_gold_indices.add(i)
                        break
    except SlotExtractionError as exc:
        return ExtractionMetrics(precision=None, recall=None, f1=None, error=str(exc))

    precision = true_positives / predicted_count if predicted_count else 0.0
    recall = true_positives / gold_count if gold_count else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0
    return ExtractionMetrics(precision=precision, recall=recall, f1=f1)


def evaluate_recent_violations(db: Session, limit: int = 20) -> dict:
    logs = (
        db.execute(select(ValidationLog).order_by(ValidationLog.id.desc()).limit(limit))
        .scalars()
        .all()
    )
    if not logs:
        return {"violation_count": 0, "logged_iterations": 0}

    total_violations = sum(len(log.violations) for log in logs)
    resolved = sum(1 for log in logs if log.resolved)
    return {
        "violation_count": total_violations,
        "resolved_rate": round(resolved / len(logs), 2),
        "logged_iterations": len(logs),
    }
