"""Turns a validated ItineraryItem list into a day-by-day natural-language
narrative using OpenAI.

Every displayed fact — place name, time period, arrival time, reservation
badge, selection reason — is rendered deterministically from the actual
itinerary/place/selection data, never generated by the model. The LLM's only
job is to weave those given facts into readable Korean prose per day; it is
explicitly instructed not to invent details (e.g. menu recommendations) that
aren't present in the source data."""

import json
from dataclasses import asdict, dataclass, field
from datetime import time as dtime
from typing import Sequence

import openai

from app.models.itinerary_item import ItineraryItem, ReservationNeeded
from app.models.place import Place
from app.schemas.narration import NarrativeOutput
from app.services.llm_client import LLMCallError, call_structured, default_client

DEFAULT_MODEL = "gpt-4o"
DEFAULT_MAX_TOKENS = 4096
DEFAULT_MAX_RETRIES = 2

_RESERVATION_BADGES: dict[ReservationNeeded, str] = {
    ReservationNeeded.required: "필수",
    ReservationNeeded.recommended: "권장",
    ReservationNeeded.unnecessary: "불필요",
}


class NarrationError(RuntimeError):
    """Raised when narrative generation fails after exhausting all retries."""


@dataclass
class ItemNarrative:
    place_id: int
    place_name: str
    time_period: str
    arrival_time: str  # ISO 8601 datetime, for machine consumption
    arrival_time_label: str  # natural Korean phrasing, e.g. "10시 23분"
    reservation_badge: str
    selection_reason: str | None
    lat: float
    lng: float


@dataclass
class DayNarrative:
    day_index: int
    narrative: str
    items: list[ItemNarrative] = field(default_factory=list)


@dataclass
class ItineraryNarrative:
    days: list[DayNarrative] = field(default_factory=list)


_FOOD_PRIMARY_TYPES = frozenset({"restaurant", "cafe", "bakery"})


def _time_period(t: dtime, place: Place | None = None) -> str:
    """Buckets an arrival time into a display label. When `place` is a food
    stop, distinguishes 아침/점심/저녁 from the surrounding 오전/오후 attraction
    buckets so the frontend can tell a meal item apart from a sightseeing
    item that merely happens to fall in the same half of the day."""
    if place is not None and (place.primary_type or "") in _FOOD_PRIMARY_TYPES:
        if t.hour < 11:
            return "아침"
        if t.hour < 15:
            return "점심"
        return "저녁"
    if t.hour < 12:
        return "오전"
    if t.hour < 18:
        return "오후"
    return "저녁"


def _format_time_korean(t: dtime) -> str:
    if t.minute == 0:
        return f"{t.hour}시"
    return f"{t.hour}시 {t.minute}분"


def _build_item_narrative(
    item: ItineraryItem, places_by_id: dict[int, Place], selection_reasons: dict[int, str]
) -> ItemNarrative:
    place = places_by_id[item.place_id]
    return ItemNarrative(
        place_id=item.place_id,
        place_name=place.name,
        time_period=_time_period(item.arrival_time.time(), place),
        arrival_time=item.arrival_time.isoformat(),
        arrival_time_label=_format_time_korean(item.arrival_time.time()),
        reservation_badge=_RESERVATION_BADGES[item.reservation_needed],
        selection_reason=selection_reasons.get(item.place_id),
        lat=place.lat,
        lng=place.lng,
    )


def _group_by_day(itinerary: Sequence[ItineraryItem]) -> dict[int, list[ItineraryItem]]:
    by_day: dict[int, list[ItineraryItem]] = {}
    for item in itinerary:
        by_day.setdefault(item.day_index, []).append(item)
    for items in by_day.values():
        items.sort(key=lambda it: it.order_in_day)
    return by_day


def _fallback_narrative(items: Sequence[ItemNarrative]) -> str:
    parts = [f"{item.time_period} - {item.place_name}(도착 {item.arrival_time_label})" for item in items]
    return " → ".join(parts)


_SYSTEM_PROMPT = """당신은 확정된 여행 일정을 자연스러운 한국어 서사로 정리하는 도우미입니다.

입력으로 day별 방문 장소 목록을 받습니다. 각 장소에는 시간대(아침/오전/점심/오후/저녁 중
하나 — 아침·점심·저녁은 식사 장소, 오전·오후는 관광/활동 장소를 뜻합니다), 도착 시각,
장소명, 예약 필요성 뱃지(필수/권장/불필요), 그리고 있다면 이 장소를 고른 이유가 함께
주어집니다.

규칙:
1. 각 day에 대해 "N일차: 아침 - 장소A(도착 8시 30분) → 오전 - 장소B(도착 10시) → 점심 -
   장소C(도착 12시 30분) → ..."처럼 시간 흐름을 따라가며 하루의 식사와 관광 리듬이
   느껴지는 자연스러운 문장으로 서술하세요. 방문 순서와 도착 시각은 주어진 데이터를
   정확히 반영해야 합니다.
2. 오직 주어진 사실(장소명, 시간대, 도착 시각, 예약 필요성, 선정 이유)만 사용하세요.
   메뉴 추천, 실제로 주어지지 않은 세부 묘사, 방문하지 않은 장소 등 데이터에 없는
   내용을 지어내지 마세요.
3. 선정 이유가 주어진 장소는 왜 이 장소를 방문하는지 문장에 자연스럽게 녹여내세요.
4. 예약 필요성이 "필수"인 장소는 예약이 필요하다는 점을 문장에서 짚어주세요.

반드시 주어진 JSON 스키마에 맞는 형식으로만 응답하세요."""


def _format_day_facts(day_index: int, items: Sequence[ItemNarrative]) -> str:
    lines = [f"[{day_index + 1}일차]"]
    for item in items:
        reason_part = f", 선정 이유: {item.selection_reason}" if item.selection_reason else ""
        lines.append(
            f"- {item.time_period} {item.arrival_time_label} {item.place_name} "
            f"(예약 {item.reservation_badge}{reason_part})"
        )
    return "\n".join(lines)


def _build_prompt(items_by_day: dict[int, list[ItemNarrative]]) -> str:
    return "\n\n".join(
        _format_day_facts(day_index, items) for day_index, items in sorted(items_by_day.items())
    )


class ItineraryNarrator:
    def __init__(
        self,
        client: openai.OpenAI | None = None,
        *,
        model: str = DEFAULT_MODEL,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        max_retries: int = DEFAULT_MAX_RETRIES,
        retry_delay_seconds: float = 1.0,
    ) -> None:
        self._client = client or default_client()
        self._model = model
        self._max_tokens = max_tokens
        self._max_retries = max_retries
        self._retry_delay_seconds = retry_delay_seconds

    def narrate(
        self,
        itinerary: Sequence[ItineraryItem],
        places_by_id: dict[int, Place],
        selection_reasons: dict[int, str] | None = None,
    ) -> ItineraryNarrative:
        selection_reasons = selection_reasons or {}
        if not itinerary:
            return ItineraryNarrative(days=[])

        items_by_day: dict[int, list[ItemNarrative]] = {
            day_index: [_build_item_narrative(item, places_by_id, selection_reasons) for item in items]
            for day_index, items in _group_by_day(itinerary).items()
        }

        narrative_by_day = self._get_narrative_text(items_by_day)

        days = [
            DayNarrative(
                day_index=day_index,
                narrative=narrative_by_day.get(day_index) or _fallback_narrative(items),
                items=items,
            )
            for day_index, items in sorted(items_by_day.items())
        ]
        return ItineraryNarrative(days=days)

    def _get_narrative_text(self, items_by_day: dict[int, list[ItemNarrative]]) -> dict[int, str]:
        prompt = _build_prompt(items_by_day)

        try:
            output: NarrativeOutput = call_structured(
                self._client,
                model=self._model,
                system_prompt=_SYSTEM_PROMPT,
                user_prompt=prompt,
                output_model=NarrativeOutput,
                schema_name="itinerary_narrative",
                max_tokens=self._max_tokens,
                max_retries=self._max_retries,
                retry_delay_seconds=self._retry_delay_seconds,
            )
        except LLMCallError as exc:
            raise NarrationError(str(exc)) from exc

        valid_day_indices = set(items_by_day)
        # Defense against a hallucinated day_index not present in the itinerary.
        return {day.day_index: day.narrative for day in output.days if day.day_index in valid_day_indices}


narrator = ItineraryNarrator()


def narrate(
    itinerary: Sequence[ItineraryItem],
    places_by_id: dict[int, Place],
    selection_reasons: dict[int, str] | None = None,
) -> ItineraryNarrative:
    return narrator.narrate(itinerary, places_by_id, selection_reasons)


def export_json(narrative: ItineraryNarrative) -> str:
    return json.dumps(asdict(narrative), ensure_ascii=False, indent=2)


def export_markdown(narrative: ItineraryNarrative) -> str:
    lines: list[str] = []
    for day in narrative.days:
        lines.append(f"## {day.day_index + 1}일차")
        lines.append("")
        lines.append(day.narrative)
        lines.append("")
        for item in day.items:
            reason_part = f" — {item.selection_reason}" if item.selection_reason else ""
            lines.append(
                f"- **{item.time_period} {item.arrival_time_label}** {item.place_name} "
                f"`[예약 {item.reservation_badge}]`{reason_part}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
