from pydantic import BaseModel, ConfigDict


class DayNarrativeText(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day_index: int
    narrative: str


class NarrativeOutput(BaseModel):
    """Shape returned directly by the LLM — prose only. Every other field
    (place name, arrival time, reservation badge, selection reason) is
    code-authoritative and merged in afterward, not generated by the model."""

    model_config = ConfigDict(extra="forbid")

    days: list[DayNarrativeText]
