"""add primary_type to places

Revision ID: 3f30fc145564
Revises: c9fe629dcdc7
Create Date: 2026-07-02 14:18:15.603169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f30fc145564'
down_revision = 'c9fe629dcdc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('primary_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'primary_type')
    # ### end Alembic commands ###
