"""add is_media to chat_messages

Revision ID: 830386014486
Revises: dcd348acfbc4
Create Date: 2026-07-02 13:25:12.635302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830386014486'
down_revision = 'dcd348acfbc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_media', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_media')
    # ### end Alembic commands ###
