"""add place_search_cache table

Revision ID: c9fe629dcdc7
Revises: 5e088f3a880e
Create Date: 2026-07-02 13:50:47.351375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fe629dcdc7'
down_revision = '5e088f3a880e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('place_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text', 'search_type', 'category', name='uq_place_search_cache_query')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_search_cache')
    # ### end Alembic commands ###
